# lang.py
strings = {
    "id": {
        "title": "🧭 SIMPEL – Cek Bantuan Sosial yang Mungkin Anda Dapat",
        "subtitle": "Jawab 7 pertanyaan singkat di bawah ini. **Data Anda tidak disimpan.**",
        "caption": "ℹ️ Kriteria yang digunakan adalah penyederhanaan untuk simulasi. Klik **sumber resmi** di setiap program untuk informasi lengkap.",
        "q1": "1. Rata‑rata pendapatan keluarga per bulan?",
        "q2": "2. Jumlah anggota keluarga (termasuk Anda)?",
        "q3": "3. Apakah ada anak usia sekolah (7–18 tahun) di keluarga?",
        "q4": "4. Apakah ada anak balita (0–6 tahun) atau ibu hamil?",
        "q5": "5. Apakah ada anggota keluarga lanjut usia (≥60 tahun)?",
        "q6": "6. Apakah ada anggota keluarga dengan disabilitas berat?",
        "q7": "7. Jenis dinding terluas rumah Anda?",
        "income_options": ["< Rp500.000", "Rp500.000 – Rp1.000.000", "Rp1.000.000 – Rp2.000.000", "> Rp2.000.000"],
        "family_options": ["1", "2", "3", "4", "5 atau lebih"],
        "wall_options": ["Tembok", "Semi permanen (setengah tembok)", "Papan/kayu", "Bambu/lainnya"],
        "yes": "Ya",
        "no": "Tidak",
        "btn": "🔍 Cek Bantuan yang Mungkin Saya Dapat",
        "result_title": "📋 Hasil Pemeriksaan",
        "success_msg": "Berdasarkan informasi Anda, Anda **mungkin** memenuhi syarat untuk {} program berikut.",
        "no_result": "Berdasarkan data yang Anda masukkan, saat ini tidak terdeteksi program yang sesuai. Namun, ini hanya simulasi. Silakan kunjungi kelurahan untuk informasi lebih lanjut.",
        "why": "Mengapa?",
        "desc": "Deskripsi",
        "docs": "Dokumen yang harus disiapkan",
        "place": "Ke mana harus pergi",
        "source": "Sumber resmi",
        "disclaimer": "⚠️ **Peringatan Penting:** Hasil ini **bukan keputusan resmi** dan hanya bersifat simulasi. Kriteria sebenarnya bisa lebih kompleks dan dapat berubah sewaktu‑waktu. **Harap verifikasi langsung ke kelurahan atau dinas sosial terdekat.** Ini adalah alat bantu, bukan penentu akhir.",
        "print_tip": "💡 Tips: Anda bisa mencetak halaman ini (Ctrl+P) untuk dibawa ke kelurahan sebagai panduan awal.",
        "reset": "🔄 Mulai Ulang",
        "lang_label": "🌐 Bahasa"
    },
    "en": {
        "title": "🧭 SIMPEL – Check Social Benefits You May Qualify For",
        "subtitle": "Answer 7 simple questions below. **Your data is not stored.**",
        "caption": "ℹ️ Criteria are simplified for simulation purposes. Click **official source** in each program for complete information.",
        "q1": "1. Average monthly household income?",
        "q2": "2. Number of family members (including you)?",
        "q3": "3. Is there a school‑age child (7–18 years) in the family?",
        "q4": "4. Is there a toddler (0–6 years) or a pregnant woman?",
        "q5": "5. Is there an elderly family member (≥60 years)?",
        "q6": "6. Is there a family member with a severe disability?",
        "q7": "7. Main material of your house walls?",
        "income_options": ["< Rp500,000", "Rp500,000 – Rp1,000,000", "Rp1,000,000 – Rp2,000,000", "> Rp2,000,000"],
        "family_options": ["1", "2", "3", "4", "5 or more"],
        "wall_options": ["Brick", "Semi‑permanent (half‑brick)", "Wood planks", "Bamboo / Other"],
        "yes": "Yes",
        "no": "No",
        "btn": "🔍 Check Benefits I May Qualify For",
        "result_title": "📋 Check Results",
        "success_msg": "Based on your information, you **may** qualify for the following {} program(s).",
        "no_result": "Based on the data you entered, no matching program was detected. However, this is only a simulation. Please visit your village office for further information.",
        "why": "Why?",
        "desc": "Description",
        "docs": "Required documents",
        "place": "Where to go",
        "source": "Official source",
        "disclaimer": "⚠️ **Important Notice:** This result is **not an official decision** and is only a simulation. Actual criteria may be more complex and subject to change. **Please verify directly at the village office or local social services.** This is a helper tool, not a final decision.",
        "print_tip": "💡 Tip: You can print this page (Ctrl+P) to take to the village office as a guide.",
        "reset": "🔄 Start Over",
        "lang_label": "🌐 Language"
    }
}